title: bitacora
baseurl: ""
url: "http://lvm.github.io/blog"

date_format: "%Y-%m-%d"
permalink:       /:title.html
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

google_analytics:

# Build settings
markdown:     kramdown
# redcarpet:
#   extensions: ['smart', 'tables', 'with_toc_data']
